version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./src:/app # ソースコードをコンテナにマウント
      - go-modules:/go/pkg/mod
    working_dir: /app
    environment:
      - GO_ENV=development
    command: ['air'] # ホットリロードを実行
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:15
  #   restart: always
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   ports:
  #     - '5432:5432'

volumes:
  go-modules:
