version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.2.0
  aws-ecr: circleci/aws-ecr@9.4.0
  aws-ecs: circleci/aws-ecs@6.0.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                role_arn: ${AWS_ECR_ROLE_ARN}
          context: aws-dev
          dockerfile: Dockerfile
          path: .
          repo: '${PROJECT_NAME}-ecr'
          tag: 'latest'
      - aws-ecs/deploy_service_update:
          auth:
            - aws-cli/setup:
                role_arn: ${AWS_ECS_ROLE_ARN}
          context: aws-dev
          cluster: ${PROJECT_NAME}-cluster
          service_name: ${PROJECT_NAME}-service
          family: ${PROJECT_NAME}-task
          container_image_name_updates: container=${PROJECT_NAME}-container,tag=latest
          requires:
            - aws-ecr/build_and_push_image
