version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.4.0
  aws-cli: circleci/aws-cli@5.2.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          account_id: ${AWS_ACCOUNT_ID}
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::101681942065
          context: aws-dev
          create_repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: my-go-api
          tag: '$CIRCLE_SHA1'
