version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws-dev
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: 'my-go-api'
          tag: '$CIRCLE_SHA1'
      # - aws-ecs/deploy-service-update:
      #     requires:
      #       - aws-ecr/build-and-push-image
      #     family: 'my-go-api-task'
      #     cluster-name: 'my-go-api-cluster'
      #     service-name: 'my-go-api-service'
      #     container-image-name-updates: 'container=my-go-api,tag=${CIRCLE_SHA1}'
